avance2/materiales3c-main/api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [

]

avance2/materiales3c-main/cdplaest/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('core/', include("core.urls")),
    path('', include("home.urls")),

]

avance2/materiales3c-main/core/urls.py
from django.urls import path

from core import views

from .models import *

app_name = "core"
urlpatterns = [
##Clientes
path('list/clientes/', views.ListClientes.as_view(), name="List_Clientes"),
path('create/cliente/', views.createCliente.as_view(), name="createCliente"),
path('detail/cliente/<int:pk>/', views.DetailClientes.as_view(), name="detailCliente"),
path('update/cliente/<int:pk>/', views.UpdateCliente.as_view(), name="updateCliente"),
path('delete/cliente/<int:pk>/', views.DeleteCliente.as_view(), name="deleteCliente"),

##Tipos
path('list/tipos/', views.ListTipo.as_view(), name="list_tipos"),
path('create/tipo/', views.CreateTipo.as_view(), name="create_tipo"),
path('detail/tipo/<int:pk>/', views.DetailTipo.as_view(), name="detail_tipo"),
path('update/tipo/<int:pk>/', views.UpdateTipo.as_view(), name="update_tipo"),
path('delete/tipo/<int:pk>/', views.DeleteTipo.as_view(), name="delete_tipo"),

##Lugar
path('list/lugar/', views.ListLugar.as_view(), name="listLugar"),
path('create/lugar/', views.CreateLugar.as_view(), name="create_lugar"),
path('detail/lugar/<int:pk>/', views.DetailLugar.as_view(), name="detail_lugar"),
path('update/lugar/<int:pk>/', views.UpdateLugar.as_view(), name="update_lugar"),
path('delete/lugar/<int:pk>/', views.DeleteLugar.as_view(), name="delete_lugar"),



]

avance2/materiales3c-main/core/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.



class Clientes(models.Model):
    id_cliente = models.AutoField(primary_key=True, db_column='ID_Cliente')  # Field name made lowercase.
    nombre = models.CharField(db_column='Nombre', max_length=255, blank=True, null=True)  # Field name made lowercase.
    telefono = models.CharField(max_length=255, blank=True, null=True)
    correo = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Clientes'


class Lugar(models.Model):
    codigo = models.AutoField(primary_key=True)
    num_calle = models.CharField(max_length=10)
    colonia = models.CharField(max_length=20)
    codigo_postal = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = 'lugar'


class Tipos(models.Model):
    codigo = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=20)
    descripcion = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'tipos'

avance2/materiales3c-main/core/forms.py
from django import forms

from .models import *


class ClientesForm(forms.ModelForm):
    class Meta:
        model = Clientes
        fields = "__all__"
        exclude = ["id_cliente"]
        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del cliente"}),
            "telefono": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el número de teléfono"}),
            "correo": forms.EmailInput(attrs={"type": "email", "class": "form-control", "placeholder": "Ingrese el correo electrónico"}),
        }

class UpdateClientesForm(forms.ModelForm):
    class Meta:
        model = Clientes
        fields = "__all__"
        exclude = ["ID_Cliente"]
        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del cliente"}),
            "telefono": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el número de teléfono"}),
            "correo": forms.EmailInput(attrs={"type": "email", "class": "form-control", "placeholder": "Ingrese el correo electrónico"}),
        }

class LugarForm(forms.ModelForm):
    class Meta:
        model = Lugar
        fields = "__all__"
        exclude = ["codigo"]
        widgets = {
            "num_calle": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el número de calle"}),
            "colonia": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre de la colonia"}),
            "codigo_postal": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el código postal"}),
        }

class UpdateLugarForm(forms.ModelForm):
    class Meta:
        model = Lugar
        fields = "__all__"
        exclude = ["codigo"]
        widgets = {
            "num_calle": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el número de calle"}),
            "colonia": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre de la colonia"}),
            "codigo_postal": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el código postal"}),
        }

class TiposForm(forms.ModelForm):
    class Meta:
        model = Tipos
        fields = "__all__"
        exclude = ["codigo"]
        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del tipo"}),
            "descripcion": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese la descripción del tipo"}),
        }

class UpdateTiposForm(forms.ModelForm):
    class Meta:
        model = Tipos
        fields = "__all__"
        exclude = ["codigo"]
        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del tipo"}),
            "descripcion": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese la descripción del tipo"}),
        }

avance2/materiales3c-main/core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import *
from .models import *

# Create your views here.

##Estadio

class ListClientes(generic.View):
    template_name = "core/list_Clientes.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Clientes.objects.all()
        self.context = {
            "Clientes": queryset  
        }
        return render(request, self.template_name, self.context)



class DetailClientes(generic.DetailView):
    template_name = "core/detailCliente.html"
    model = Clientes


class createCliente(generic.CreateView):
    template_name = "core/createCliente.html"
    model = Clientes
    form_class = ClientesForm
    success_url = reverse_lazy("core:List_Clientes")


class UpdateCliente(generic.UpdateView):
    template_name = "core/UpdateCliente.html"
    model = Clientes
    form_class = UpdateClientesForm
    success_url = reverse_lazy("core:List_Clientes")

class DeleteCliente(generic.DeleteView):
    template_name = "core/deleteCliente.html"
    model = Clientes
    success_url = reverse_lazy("core:List_Clientes")


##Equipos

class ListTipo(generic.View):
    template_name = "core/listTipo.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Tipos.objects.all()
        self.context = {
            "Tipos": queryset
        }
        return render(request, self.template_name,self.context)
    
class CreateTipo(generic.CreateView):
    template_name = "core/create_tipo.html"
    model = Tipos
    form_class = TiposForm
    success_url = reverse_lazy("core:list_tipos")

    def form_valid(self, form):
        # Aquí puedes realizar operaciones adicionales si es necesario
        return super().form_valid(form)




class DetailTipo(generic.DetailView):
    template_name = "core/detailTipo.html"
    model = Tipos

class UpdateTipo(generic.UpdateView):
    template_name = "core/UpdateTipo.html"
    model = Tipos
    form_class = UpdateTiposForm
    success_url = reverse_lazy("core:list_tipos")

class DeleteTipo(generic.DeleteView):
    template_name = "core/deleteTipo.html"
    model = Tipos
    success_url = reverse_lazy("core:list_tipos")

##Ciudades

class ListLugar(generic.View):
    template_name = "core/listLugar.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Lugar.objects.all()
        self.context = {
            "Lugar": queryset
        }
        return render(request, self.template_name,self.context)

class CreateLugar(generic.CreateView):
    template_name = "core/createLugar.html"
    model = Lugar
    form_class = LugarForm
    success_url = reverse_lazy("core:listLugar")

class DetailLugar(generic.DetailView):
    template_name = "core/detailLugar.html"
    model = Lugar

class UpdateLugar(generic.UpdateView):
    template_name = "core/UpdateLugar.html"
    model = Lugar
    form_class = UpdateLugarForm
    success_url = reverse_lazy("core:listLugar")

class DeleteLugar(generic.DeleteView):
    template_name = "core/deleteLugar.html"
    model = Lugar
    success_url = reverse_lazy("core:listLugar")
    
    

avance2/materiales3c-main/templates/core/UpdateLugar.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Lugar
{% endblock title %}

{% block content %}
<h1>Actualizar Lugar</h1>
<form method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-outline-primary">Actualizar Lugar</button>
  <a href="{% url 'core:listLugar' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

avance2/materiales3c-main/templates/core/UpdateTipo.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Tipo
{% endblock title %}

{% block content %}
<h1>Actualizar Tipo</h1>
<form method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-outline-primary">Actualizar Tipo</button>
  <a href="{% url 'core:list_tipos' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

avance2/materiales3c-main/templates/core/createLugar.html
{% extends "base/base.html" %}

{% block title %}
  Anadir City
{% endblock title %}

{% block content %}
<h1>Agregar Ciudad</h1>
<form method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-outline-success">Agregar Ciudad</button>
  <a href="{% url 'core:listLugar' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

avance2/materiales3c-main/templates/core/create_tipo.html
{% extends "base/base.html" %}

{% block title %}
  Anadir Tipo de material
{% endblock title %}

{% block content %}
<form action="" method="post" class="form">
  {% csrf_token %}
  {{ form.nombre.label_tag }}
  {{ form.nombre }}
  {{ form.descripcion.label_tag }}
  {{ form.descripcion }}
  <button type="submit" class="btn btn-outline-success">Agregar Tipo</button>
  <a href="{% url 'core:list_tipos' %}" class="btn btn-outline-warning">Cancelar</a>
</form>

{% endblock content %}

avance2/materiales3c-main/templates/core/deleteCliente.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Cliente
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Estás seguro de que deseas eliminar al cliente "{{ object }}"?
        <button type="submit" class="btn btn-outline-danger">Eliminar Cliente</button>
        <a href="{% url 'core:List_Clientes'%}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

avance2/materiales3c-main/templates/core/deleteLugar.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Lugar
{% endblock title %}

{% block content %}
<h1>Eliminar Lugar</h1>
<p>¿Estás seguro de que quieres eliminar el lugar "{{ Lugar.colonia }}"?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-danger">Sí, eliminar</button>
  <a href="{% url 'core:listLugar' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

avance2/materiales3c-main/templates/core/deleteTipo.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Equipo
{% endblock title %}

{% block content %}
<h1>Eliminar Equipo</h1>
<p>¿Estás seguro de que quieres eliminar el equipo "{{ object.nombre }}"?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-danger">Eliminar Equipo</button>
  <a href="{% url 'core:list_tipos' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

avance2/materiales3c-main/templates/core/detailCliente.html
{% extends "base/base.html" %}

{% block title %}
  DETAIL CLIENTE VIEW
{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ object.nombre }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>Nombre del Cliente: {{ object.nombre }}</strong> <br>
          Teléfono: {{ object.telefono }} <br>
          Correo Electrónico: {{ object.correo }}
        </div>
      </div>
    </div>
</div>

<a href="{% url 'core:List_Clientes' %}">Volver a la lista de clientes</a>
{% endblock content %}

avance2/materiales3c-main/templates/core/detailLugar.html
{% extends "base/base.html" %}

{% block title %}
  DETAIL LUGAR VIEW
{% endblock title %}

{% block content %}
<h1>Detalles del Lugar</h1>
  <p>Número de Calle: {{ lugar.num_calle }}</p>
  <p>Colonia: {{ lugar.colonia }}</p>
  <p>Código Postal: {{ lugar.codigo_postal }}</p>
  <a href="{% url 'core:listLugar' %}" class="btn btn-outline-warning">Volver</a>
{% endblock content %}

avance2/materiales3c-main/templates/core/detailTipo.html
{% extends "base/base.html" %}

{% block title %}
  DETAIL TIPO
{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ object.nombre }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>Descripción del tipo: {{ object.descripcion }}</strong>
        </div>
      </div>
    </div>
  </div>
  
  <a href="{% url 'core:list_tipos' %}">Volver a la lista</a>
{% endblock content %}

avance2/materiales3c-main/templates/core/listTipo.html
{% extends 'base/base.html' %}

{% block title %} Lista de Tipos {% endblock title %}

{% block content %}


<a href="{% url 'core:create_tipo' %}" class="btn btn-outline-success form-control">Añadir nuevo tipo</a>
<h1>Listado de Tipos</h1>
<table class="table">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for tipo in Tipos %}
            <tr>
                <td>{{ tipo.codigo }}</td>
                <td>{{ tipo.nombre }}</td>
                <td>{{ tipo.descripcion }}</td>
                <td>
                    <a href="{% url 'core:detail_tipo' tipo.codigo %}" class="btn btn-outline-info">Detalles</a>
                    <a href="{% url 'core:update_tipo' tipo.codigo %}" class="btn btn-outline-warning">Actualizar</a>
                    <a href="{% url 'core:delete_tipo' tipo.codigo %}" class="btn btn-outline-danger">Eliminar</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>


    
{% endblock content %}

avance2/materiales3c-main/templates/core/list_Clientes.html
{% extends 'base/base.html' %}
{% block title %} LIST Clients {% endblock title %}

{% block content %}
    <a href="{% url 'core:createCliente' %}" class="btn btn-outline-success form-control">Anadir nuevo Cliente</a>
    <h1>Listado de Clientes</h1>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nombre del cliente</th>
                <th>Teléfono del cliente</th>
                <th>Correo del cliente</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for Clientes in Clientes %}  
                <tr>
                    <td>{{ Clientes.nombre }}</td>
                    <td>{{ Clientes.telefono }}</td>
                    <td>{{ Clientes.correo }}</td>
                    <td>
                        <a href="{% url 'core:detailCliente' Clientes.id_cliente %}" class="btn btn-outline-info">Detalles</a>
                        <a href="{% url 'core:updateCliente' Clientes.id_cliente %}" class="btn btn-outline-warning">Actualizar</a>
                        <a href="{% url 'core:deleteCliente' Clientes.id_cliente %}" class="btn btn-outline-danger">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}